[cursor]
style = "Beam"

[font]
size = 16.0

[font.bold]
family = "Cica"
style = "Bold"

[font.bold_italic]
family = "Cica"
style = "Bold Italic"

[font.italic]
family = "Cica"
style = "Italic"

[font.normal]
family = "Cica"
style = "Regular"

[font.offset]
x = 1
y = 1

[selection]
save_to_clipboard = true

[window]
opacity = 0.92

[window.padding]
x = 2
y = 2

[terminal]

[colors.bright]
black = "0x899BA6"
blue = "0x83AFE5"
cyan = "0x7FC1CA"
green = "0xA8CE93"
magenta = "0xD18EC2"
red = "0xF2C38F"
white = "0xE6EEF3"
yellow = "0xDADA93"

[colors.normal]
black = "0x3C4C55"
blue = "0x83AFE5"
cyan = "0x7FC1CA"
green = "0xA8CE93"
magenta = "0x9A93E1"
red = "0xDF8C8C"
white = "0xC5D4DD"
yellow = "0xDADA93"

[colors.primary]
background = "0x0C1C25"
foreground = "0xC5D4DD"
